version: '3.3'

services:
  backend:
    container_name: "backend"
    restart: always
    image: pedropeguimaraes/news_backend:v1
    ports:
      - "5000:5000"
    environment:
      DB_USER: root
      DB_PASSWORD: op7yZkjqCmS02y6G

  frontend:
    container_name: "frontend"
    restart: always
    image: pedropeguimaraes/news_frontend:v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      API_NEWS_URL: http://backend:5000/news
