name: Docker Build Images

on:
  workflow_dispatch:
    inputs:
        manual_deploy:
          description: "Manual Deploy"
          required: true
          type: boolean
          default: true
  push:
    branches:
      - project

jobs:
  build:
    runs-on: ubuntu-latest
    environment: project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/news_frontend:latest

    - name: Build and push Docker image Backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/news_backend:latest
